test/objects/Product__c.object
<CustomObject>
    <description>Таблица для хранения информации о товарах</description>
    <fields>
        <fullName>Type__c</fullName>
        <description>Тип</description>
        <inlineHelpText>Тип товара</inlineHelpText>
        <label>Тип</label>
        <picklist>
            <picklistValues>
                <fullName>ПС</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>ДП</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>СА</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>КП</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>КТ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Товар</label>
    <nameField>
        <label>Имя</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Товары (Standard)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

test/classes/GoodsListController.cls
public with sharing class GoodsListController {

    public GoodsListController(ApexPages.StandardSetController controller) {
        product = new Product__c();
        showList = false;
    }

    public Product__c product{get;set;}
    
    public String selType{get;set;}
    
    public Boolean showList {get;set;}
    
    public String errorMessage = '';
    
    public pagereference save(){
        product.Type__c = selType;
        try{
            insert product;             
            String id = ApexPages.CurrentPage().getparameters().get('id');
            pagereference ref = new pageReference('/'+product.id);
            ref.setRedirect(true);            
            return ref;
        
        }
            catch(Exception errMsg){
                ApexPages.addMessages(errMsg);
                showList = true;
        }
            product = new Product__c();
//            product = null;
            return null;        
        }
}