test/objects/Product__c.object
<CustomObject>
    <description>Таблица для хранения информации о товарах</description>
    <fields>
        <fullName>Available__c</fullName>
        <defaultValue>true</defaultValue>
        <description>В наличии</description>
        <inlineHelpText>Признак наличия товара</inlineHelpText>
        <label>В наличии</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_added__c</fullName>
        <description>Дата добавления</description>
        <inlineHelpText>Дата добавления товара</inlineHelpText>
        <label>Дата добавления</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <description>Цена</description>
        <inlineHelpText>Цена товара</inlineHelpText>
        <label>Цена</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Количество</description>
        <inlineHelpText>Количество товара</inlineHelpText>
        <label>Количество</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Release_date__c</fullName>
        <description>Дата выпуска</description>
        <inlineHelpText>Дата выпуска товара</inlineHelpText>
        <label>Дата выпуска</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Тип</description>
        <inlineHelpText>Тип товара</inlineHelpText>
        <label>Тип</label>
        <picklist>
            <picklistValues>
                <fullName>ПС</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>ДП</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>СА</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>КП</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>КТ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Товар</label>
    <nameField>
        <label>Имя</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Товары (Standard)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

test/classes/GoodsVFController.cls
public with sharing class GoodsVFController {

    public string Result { get; set; }

    public PageReference whatever() {
        PageReference pageRef = null;
        return new PageReference('/a05/e?retURL=/apex/{!$CurrentPage.Name}');
    }

    public PageReference callout() {
        return null;
    }

    public Integer noOfRecords {get; set;}
    public Integer size {get;set;}
    public List<SelectOption> paginationSizeOptions{get;set;}

    public List<Product__c> Goods { get{
        return (List<Product__c>) setCon.getRecords();
    } set; }

    public static Date parseDate(String inDate) {
        Date    dateRes    = null;
        try {
            String candDate    = inDate.substring(0,Math.min(10,inDate.length()));
            dateRes    = Date.parse(candDate);
        }
        catch (Exception e) {}
     
        if (dateRes == null) {
            try {
                String candDate    = inDate.substring(0,10);
                dateRes            = Date.valueOf(candDate);
            }
            catch (Exception e) {}
        }    
        return dateRes;
    }

    public String SearchDateStr { get; set; }
    
    public PageReference cancel() {
        return null;
    }
    
    public void SearchGoods() {
        setCon = null;
        setCon.setPageNumber(1);
    }
    
    //sdjshdksd
    
    public ApexPages.StandardSetController setCon {
        get{
        system.debug(LoggingLevel.Error, '>> SelectedRecordId = "'+SelectedRecordId+'"');
        if(setCon == null){
            String SearchQuery = SearchGoodsStr == null ? '%%' : '%'+SearchGoodsStr+'%';    
            if (SearchDateStr == null) {SearchDateStr = '';}
            if (SearchDateStr == '') {
                AvailableGoods = [SELECT Id, Name, Price__c, Quantity__c, Type__c, Date_added__c, Release_date__c, Available__c FROM Product__c WHERE Name LIKE :SearchQuery];                                
                setCon = new ApexPages.StandardSetController(AvailableGoods );
                setCon.setPageSize(size);
                noOfRecords = setCon.getResultSize();       
        } else {            
            Date SearchQuery1 = parseDate(SearchDateStr);       
            AvailableGoods = [SELECT Id, Name, Price__c, Quantity__c, Type__c, Date_added__c, Release_date__c, Available__c FROM Product__c WHERE Date_added__c = :SearchQuery1 and Name LIKE :SearchQuery]; 
            setCon = new ApexPages.StandardSetController(AvailableGoods );
            setCon.setPageSize(size);
            noOfRecords = setCon.getResultSize();}
        }
        records = new Map<Id, Product__c>((list<Product__c>)setCon.getRecords());
        system.debug(LoggingLevel.Error, '>>SETCON RECS: '+setCon.getRecords());
        return setCon;                         
    } set; }       
 
    public String SearchGoodsStr { get; set; }     
         
    public String selectedRecordId { get; set; }      
    
    public String edtLnk4Debug { get; set; }    
       
    public List<Product__c> AvailableGoods { get; set; }      

    public Map<Id, Product__c> records {get; private set;}
       
    public GoodsVFController() {
        size=10;
        paginationSizeOptions = new List<SelectOption>();
        paginationSizeOptions.add(new SelectOption('5','5'));
        paginationSizeOptions.add(new SelectOption('10','10'));
        paginationSizeOptions.add(new SelectOption('20','20'));
        paginationSizeOptions.add(new SelectOption('50','50'));
        paginationSizeOptions.add(new SelectOption('100','100'));               
    }
        
    public PageReference DeleteGoods() {
        try {
            Product__c item = [select Id from Product__c where Id = :selectedRecordId];
            system.debug(LoggingLevel.Error, '>>OUTPUT (before del): '+setCon.getRecords());
            delete item;            
            records.remove(selectedRecordId);
            setCon = null;
            system.debug(LoggingLevel.Error, '>>OUTPUT (after del): '+setCon.getRecords());
        } catch (Exception ex) {
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage());
            ApexPages.addMessage(myMsg);
        }
        return null;
    }      

    public PageReference refreshPageSize() {
         setCon.setPageSize(size);
         return null;
    }    

}