test/objects/Product__c.object
<CustomObject>
    <description>Таблица для хранения информации о товарах</description>
    <fields>
        <fullName>Available__c</fullName>
        <defaultValue>true</defaultValue>
        <description>В наличии</description>
        <inlineHelpText>Признак наличия товара</inlineHelpText>
        <label>В наличии</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_added__c</fullName>
        <description>Дата добавления</description>
        <inlineHelpText>Дата добавления товара</inlineHelpText>
        <label>Дата добавления</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <description>Цена</description>
        <inlineHelpText>Цена товара</inlineHelpText>
        <label>Цена</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Количество</description>
        <inlineHelpText>Количество товара</inlineHelpText>
        <label>Количество</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Release_date__c</fullName>
        <description>Дата выпуска</description>
        <inlineHelpText>Дата выпуска товара</inlineHelpText>
        <label>Дата выпуска</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Тип</description>
        <inlineHelpText>Тип товара</inlineHelpText>
        <label>Тип</label>
        <picklist>
            <picklistValues>
                <fullName>ПС</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>ДП</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>СА</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>КП</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>КТ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Товар</label>
    <nameField>
        <label>Имя</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Товары (Standard)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

test/classes/testClass.cls
@isTest
private class testClass
{   
         @isTest 
         static void testDel() 
         {
             Profile profile = [select id, Name from profile where name='System Administrator'];  
             User user = new User(alias = 'Bh69', email='bothlefthands@test.com', emailencodingkey='UTF-8', lastname='Saltushechkin', languagelocalekey='en_US', localesidkey='en_US', profileid = profile.Id, timezonesidkey='America/Los_Angeles', username='bothlefthands@test.com');     
             insert user;
             System.RunAs(user){
                    Product__c item = new Product__c ( // Name, Price__c, Quantity__c, Type__c, Date_added__c, Release_date__c, Available__c
                        Name = 'Pencil',
                        Price__c =250,
                        Quantity__c = 4,
                        Type__c = 'ПС',
                        Date_added__c = Date.TODAY(),
                        Release_date__c = Date.TODAY());
                        insert item;
                 
                    Product__c item_w_err = new Product__c ( // Name, Price__c, Quantity__c, Type__c, Date_added__c, Release_date__c, Available__c
                        Name = 'Pen',
                        Price__c =133,
                        Quantity__c = 0,
                        Type__c = 'ПС',
                        Date_added__c = Date.TODAY(),
                        Release_date__c = Date.TODAY());
                        insert item_w_err;
                 
                   test.startTest();                      
                        delete item;
                 		delete item_w_err;
                   test.stopTest();  
                   List<Product__c> resultGoods = [select Id from Product__c];
                   System.assertEquals(0, resultGoods.size(), 'Goods not deleted');               
               }  
          }  
}